# Generated by Django 4.2.14 on 2024-08-02 02:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('correct_option', models.IntegerField(default=0)),
                ('comment_1', models.CharField(blank=True, max_length=100)),
                ('comment_2', models.CharField(blank=True, max_length=100)),
                ('comment_3', models.CharField(blank=True, max_length=100)),
                ('comment_4', models.CharField(blank=True, max_length=100)),
                ('audio_file_1', models.FileField(upload_to='documents/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('audio_file_2', models.FileField(upload_to='documents/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('audio_file_3', models.FileField(upload_to='documents/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('audio_file_4', models.FileField(upload_to='documents/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
