# Generated by Django 5.0.7 on 2024-08-04 19:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='slideshow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slideshow.slideshow'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_file',
            field=models.FileField(upload_to='documents/image/slide', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
