# Generated by Django 5.0.7 on 2024-08-04 20:21

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0002_picture_slideshow_alter_picture_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image_file',
        ),
        migrations.AddField(
            model_name='picture',
            name='image_field',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1024, 768], upload_to='documents/image/slide'),
        ),
    ]
