# Generated by Django 5.0.7 on 2024-08-11 19:11

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0003_remove_picture_image_file_picture_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='description',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='image_field',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1024, 768], upload_to='documents/image/slide/title'),
        ),
    ]
