# Generated by Django 5.0.7 on 2024-08-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_mediavideomodel_videomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='video_file',
            new_name='video_url',
        ),
    ]
